version: 2.0


defaults: &defaults
  docker:
    - image: circleci/python:3.7.6
  working_directory: ~/project


prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip


prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_app:
    <<: *defaults
    <<: *prepare_venv
    working_directory: ~/project/api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  build:
    <<: *defaults
    docker:
      - image: docker:19.03.12

    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build Docker Image
          command: |
            docker build -t mobile_price_api_image .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push mobile_price_api_image

  deploy:
    docker:
      - image: docker:19.03.12

    steps:
      - run:
          name: Deploy to Render
          command: |
            curl -X POST "https://api.render.com/deploy" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -d '{"image": "mobile_price_api_image"}'




workflows:
  version: 2
  mobile_price_prediction:
    jobs:
      - test_app
      - build:
          requires:
            test_app
      - deploy:
          requires:
            - build