version: '2.1'
orbs:
  node: circleci/node@5.1.0


defaults: &defaults
  docker:
    - image: circleci/python:3.7.6
  working_directory: ~/project


prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip


prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_ml_app:
    <<: *defaults
    working_directory: ~/project/api

    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  build:
    <<: *defaults

    steps:
      - setup_remote_docker:
          version: 20.10.18
          dockerfile: Dockerfile
      - checkout:
          path: ~/project
      - run:
          name: Build Docker Image
          command: |
            docker build -t mobile_price_api_image .
      - run:
          name: Tag Image
          command: |
            docker tag mobile_price_api_image mustafayevm/mobile_price_api_image
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push mustafayevm/mobile_price_api_image

  deploy_to_railway:
    <<: *defaults

    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout:
          path: ~/project
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Build and run Dockerfile
          command: |
            railway link $RAILWAY_PROJECT && railway up --detach



  deploy_to_render:
    <<: *defaults

    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout:
          path: ~/project
      # Deploy the service to Render
      - run:
          name: Deploy service to Render
          command: |
            curl -H "Authorization: Bearer $RENDER_API_KEY" \
                 -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"name":"mobile_price_api", \
                      "type":"web",\
                      "region": "us-west", \
                      "dockerImage":"mustafayevm/mobile_price_api_image:latest"}' \
                 https://render.com/api/v1/services

      # Verify the deployment
      - run:
          name: Verify deployment
          command: |
            curl -H "Authorization: Bearer $RENDER_API_KEY" \
                 https://mobile_price_api.onrender.com/






workflows:
  version: 2
  mobile_price_prediction:
    jobs:
      - test_ml_app
      - build:
          requires:
            - test_ml_app
      - deploy_to_render:
          requires:
            - build
      - deploy_to_railway:
          requires:
            - test_ml_app