version: 2


defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project


prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox



tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/



workflows:
  version: 2
  mobile_price_prediction:
    jobs:
      - test_app:
      # - deploy_app_to_render:
      #     requires:
      #       - test_app
          filters:
            branches:
              only:
                - main
      # upload after git tags are created
      # - test_and_upload_classification_model:
      #     <<: *tags_only
      # - deploy_app_container_in_render:
      #     filters:
      #       branches:
      #         only:
      #           - master